### PR TITLE
new instabot.py function and workflow

### PR DESCRIPTION
**Pull request by kemong**
modified:   instabot.py
	new file:   test.py
	deleted:    unfollowpub.py
	deleted:    userinfo.py

### CODE REVIEW

**Comment by LevPasha** [comment]
@kemong ok. this is big changes - we should test it. if all ok - i will merge it! thx for your work!

**Comment by polaroi8d** [comment]
Nice patch!

**Comment by LevPasha** [comment]
@kemong @polaroi8d the problem is - there is many conflict. @kemong i have idea for you. Change your pull. Create new folder - name if "kemong version", and put all of your files there. For some time we will connect your and my version. Users can watch your code, download it and we will integrate best part of it in me code. Ok?

**Comment by polaroi8d** [comment]
By the way, im not tested it. Its works fine?

**Comment by kemong** [comment]
@LevPasha  ok i'll try to make it modular. I'll separate my modified function and your original script, When someone want to use my method, they can call it on demand..

**Comment by kemong** [comment]
Hi pal...i've uploaded my newest codes to github...check it out!

**Comment by LevPasha** [comment]
@kemong hi. THX! I will merge it, and guys go to test it.

**Comment by LevPasha** [comment]
@kemong one more thing. Now bot look bad. To many files ib main derectory. Can you create folder "src" and put there all files except "readme.md and example.py". This will be much better! Don't forget to change "import" in example. THX!

**Pull request merged**
