### PR TITLE
Added Unfollow Whitelist

### PR DESCRIPTION
**Pull request by saphiresouldier**
There are some accounts I want to follow and the bot shouldn't unfollow them even if all other conditions for a unfollow apply.
I added an username-based whitelist to make this possible, before unfollowing the bot checks against this list and chooses another random account to unfollow if the username is on the whitelist.

The example.py file has been updated to reflect these changes.

### CODE REVIEW

**Comment by dadealer** [comment]
i will test it

**Comment by saphiresouldier** [comment]
Thank you @dadealer ! I'm running the bot with this modification for ~2 weeks now and it works well.

I might need to add a check for the special case if the bot is only following users on the whitelist and tries to unfollow, I'll check that later.

**Comment by dadealer** [comment]
At the moment It works very well. Thumbs up man.

**Comment by dadealer** [comment]
today it was stuck at the whitelist user. i think that you need to build in a counter. if 10 times a whitelist user in a row, the bot need to skip

**Comment by saphiresouldier** [comment]
Thanks @dadealer , I suspected it could happen. Will upload a fix later today!

**Comment by lotusrs** [comment]
It's awesome pull request.
Could you please update README.md?

**Comment by saphiresouldier** [comment]
I added the fix and an update to readme.md with this pull request: https://github.com/LevPasha/instabot.py/pull/391

**Comment by Ere-Eye** [comment]
The bot is stuck in a loop giving console output:

`found whitelist user, starting search again
`
for hours when I tried it.

**Comment by ampersamd** [comment]
@Ere-Eye Getting the same thing. Have only been running it for a day using the whitelist feature.

**Pull request merged**
