### PR TITLE
Fix comment, follow and like

### PR DESCRIPTION
**Pull request by nekfeu**
Delete some problems like multiple comments on same media, comment our own media, follow our own profile and like our own media.

### CODE REVIEW

**Comment by rohit366** [comment]
Hi can you please help me with the latest patched version, I am not a program and just run with basic instructions on running the bot, i would really appreciate if you can provide me the the latest files and guide on not following the same person or like the same media again and again after in following or unliking them. Another importent thing is to follow followers of a target account can we achieve that with this bot.

Thanks for your kind support and efforts.

**Comment by nekfeu** [comment]
What kind of help do you need ?
What's are your questions ?

**Comment by rohit366** [comment]
Thanks for responding soon. 

I am looking to follow the followers of a target account with conditions like the follow only those who have followed the target account 1 hour ago.

Another request would be to avoid liking and following the same media or account again after unfollowing them.

What are your thoughts on geolocation and gender based following for laser targeted following approach with this bot can this be achieved.

**Comment by rohit366** [comment]
Thanks for responding soon. 

I am looking to follow the followers of a target account with conditions like the follow only those who have followed the target account 1 hour ago.

Another request would be to avoid liking and following the same media or account again after unfollowing them.

What are your thoughts on geolocation and gender based following for laser targeted following approach with this bot can this be achieved.

**Comment by nivong** [comment]
👍

**Comment by nekfeu** [comment]
@nivong it's working fine for you?
@rohit366 : in unfollowpub.py, LevPasha show how get the follower list. From here you can follow one by one this list. For the condition : 1hour ago maximum for the moment I don't see any possibilities to do that.. sorry. 
For the second request I don't understand what do you mean. (give an example please)
Concerning geolocation, actually it's possible.
The gender... it's more complicated. You have it on your settings yes but it doesn't appear on your public scope therefore we can get it with a request profile details.

**Comment by nivong** [comment]
So far so good yes

**Comment by rohit366** [comment]
@nekfew hope my request is clear please let me if you need more info

**Comment by rohit366** [comment]
@nekfew oops I didn't noticed your previous comment. The unfollowing.py will give me a list of people I unfollowed right ? 

I want to follow people who are follower of your profile for example and I don't have you in the unfollowed.py file then how can I do that. 

I want to follow only female users from usa or australia or uk , that's what I ment for the geolocation request. How can we achieve that as you mentioned that it's possible with user I do request. 

I am running the code using the example.py file it would be great if you can guide me for adding these additional codes in the same file for easy execution as I don't know what else is needed to added to the code to achieve the results.

**Comment by rohit366** [comment]
@nekfeu let's connect over Skype for a better conversation to solve this thing. My Skype ID is rohit_366 looking forward connecting with you soon.

**Comment by nekfeu** [comment]
@rohit366  I'm very busy at this time.
Unfollowed.py allow you to unfollow each user who don't follow you. Nothing more.
But, thanks to that you can get the follower list of the user that you want. 

The gender is impossible to get, so sorry but your asking can't be done.
Take a look at the python, you could do some function by your self.

**Comment by mbaktika19** [comment]
Bro could you make this bot to comment on a media from hashtag randomly, not in accordingly? The bot seemed posting the comment on the recent or top media. So, when I had targeted only a hashtag that the media were not much developing, and I started / restarted the bot, it would try to comment on the media that already were commented in my previous session. So in some minutes I only got Keep calm - media already commented. I think this problem could be fixed by adding an option to the bot to comment media in a random way. Since I am not a programmer at all, I really hope that you can be the hero. Thank you very much

**Comment by LevPasha** [comment]
Who has already tested, everything working?

**Comment by LevPasha** [comment]
Boys and girls (ahaha), please test it, and i will merge!

**Comment by polaroi8d** [comment]
@LevPasha & @nekfeu Tested on Ubuntu 15.10 wily (x86-64) on that hash a48552c5e6b9f821b5bb0576119627106f94b2d1
Works fine :white_check_mark:

**Comment by nekfeu** [comment]
Yes @polaroi8d & @LevPasha I use it from 1 week now, it seems ok on Mac ElCaptain

**Comment by LevPasha** [comment]
@nekfeu add description to readme.

**Comment by hfmhull** [comment]
Im lost on how to use this new version. I would like to just leave a simple comment on certain tags with out doubling up on the comments. Im new to github and just want to know where to download the new version and where I input the "comment" I want left on the post?

**Comment by hfmhull** [comment]
Also everytime I try to add in the comment portion to example.py it just opens python and closes immediately. I know Im a newb!

**Pull request merged**
