### PR TITLE
Fix Couldn't find caption - not liking, change version number showing on terminal and src/instabot.py

### PR DESCRIPTION
**Pull request by LukaszChudzik**

### CODE REVIEW

**Comment by LukaszChudzik** [comment]
#278 #280

**Comment by supa4di** [comment]
it isnt goes more than 1 like and 1 follow

**Comment by LukaszChudzik** [comment]
zrzut-ekranu-2016-11-20-o-09 33 30

**Comment by supa4di** [comment]
Yes it is working, thank you so much:)

**Comment by LevPasha** [comment]
Guys, i pull something like this! str.lower => unicode.lower, unicode.lower => str.lower. Maybe it is different python version? Test it please on all python version!

https://github.com/LevPasha/instabot.py/pull/251/files

**Comment by LukaszChudzik** [comment]
# str.lower
**Work**
Python 3.5.1
**Dont' work**
Python 2.7.10

# unicode.lower
**Work**
Python 2.7.10
**Dont' work**
Python 3.5.1

**Comment by LevPasha** [comment]
@LukaszChudzik change pull to check it.

**Comment by migonin** [comment]
Looks like this PR fixes #286

**Comment by LevPasha** [comment]
@LukaszChudzik wait your code. Check py version and make different things.

**Comment by LevPasha** [comment]
@LukaszChudzik thx, wait some test!

**Comment by LevPasha** [comment]
Look like all work fine.

**Pull request merged**
