### PR TITLE
fixed AttributeError

### PR DESCRIPTION
**Pull request by nivong**
fixed AttributeError: UserInfo instance has no attribute 'get_user_id_by_login'

### CODE REVIEW

**Comment by nivong** [comment]
@nekfeu

**Comment by nekfeu** [comment]
@nivong did you have the right version of UserInfo.py?

**Comment by nivong** [comment]
I do but why do you need the userinfo file anyway?

**Comment by nekfeu** [comment]
because get_user_id_by_login is contains on this file

**Comment by nivong** [comment]
again but why would you use that user id when the user fills it in the example.py?

**Comment by nekfeu** [comment]
I don't use these links because I know they don't work.
I use "url_user_info" just below.
The function get_user_id_by_login is on UserInfo.py because it concern infos about user so it's because of that you need this file.
I decided to use id because of changements of username are ordinary.

**Comment by LevPasha** [comment]
@nivong @nekfeu guys what happen? I don't understand what you talk about) 
Now it is all ok? I merge it?

**Comment by nekfeu** [comment]
@LevPasha no, this version is without everything i added

**Comment by LevPasha** [comment]
@nivong @nekfeu wait for ready...

**Comment by nekfeu** [comment]
@LevPasha There are no problems

**Comment by LevPasha** [comment]
@nivong @nekfeu should i merge it? What is that?

**Comment by nivong** [comment]
i reverted to the earlier version can't test now since i don't have any time.

**Comment by nekfeu** [comment]
@LevPasha if you merge this you delete the part that i did, as you want haha

**Comment by virginsince1997** [comment]
Anytime I running example.py python closes fast

**Pull request closed without merging**
