### PR TITLE
This tests for a posix environment and adds color features accordingly

### PR DESCRIPTION
**Pull request by DrCherry**
Added posix colors to the InstaBot object so I could color code the output for better legibility.  This probably won't work across platforms.  Added an environment test rendering posix color codes empty if not posix compliant.

### CODE REVIEW

**Comment by Killerherts** [comment]
what environment does this work in

**Comment by DrCherry** [comment]
I tested it with Arch Linux in a bash shell.  If the environment isn't posix, the color-coding is simply disabled.

**Comment by Killerherts** [comment]
i ran it for awhile i didn't have any issues with it  wish it was coded for windows though :+1:

**Comment by DrCherry** [comment]
You can run it in bash on windows.

**Comment by DrCherry** [comment]
@Killerherts thanks for testing in a non-posix env!  I wanted it to fail elegantly.

**Comment by DrCherry** [comment]
I'll have another pull request shortly that should work for you.

**Comment by Killerherts** [comment]
Yeah no problem most users will not even know what posix is

**Comment by DrCherry** [comment]
They shouldn't need to know, if it's a posix-compliant env then pretty colors.

**Comment by DrCherry** [comment]
https://github.com/DrCherry/instabot.py/tree/colors

**Comment by Killerherts** [comment]
let me know what else you need tested when you get next park finished I can help you out

**Comment by DrCherry** [comment]
Sure thing @Killerherts - I've pulled all the color coding into the bot object.  It should be transparent to non posix users.

**Comment by Killerherts** [comment]
How exciting I want those colors

**Comment by LevPasha** [comment]
O_o

**Comment by Killerherts** [comment]
The master speaks

**Comment by DrCherry** [comment]
Failing on the rebase.  I'm getting stuck on others' commits.   Can I just wipe out my fork and start over?

**Pull request closed without merging**
