### PR TITLE
Fixing Couldn't find caption - not liking

### PR DESCRIPTION
**Pull request by ArgonQQ**
This fixes "Couldn't find caption - not liking"

Jimmy5 found this.
https://github.com/jimmy05

### CODE REVIEW

**Comment by dannyvoid** [comment]
This doesn't always work. Some accounts work with this fix, and some only work with the original line of code.

**Comment by LevPasha** [comment]
@ArgonQQ @dannyvoid sorry guys! I don't have time to test it. We should ask author of this code. @polaroi8d ho write this code?

**Comment by polaroi8d** [comment]
@LevPasha @mmaton wrote it.

**Comment by ArgonQQ** [comment]
So? Any update on this?

**Comment by TTAAEELL** [comment]
Still getting this error with latest version of bot.

**Comment by solojungle** [comment]
Same here.

**Pull request closed without merging**
