### PR TITLE
Fixed 'caption'

### PR DESCRIPTION
**Pull request by AlexeyPetroff**
The function which supposed to like photos didn't work and almost all the time I got a message "Couldn't fin caption - not liking". I fixed it. It was a problem with split() and some stuff with decoding. Now it works perfectly

### CODE REVIEW

**Comment by LevPasha** [comment]
@AlexeyPetroff привет, не вижу изменения (напиши строку куда смотреть). Спасибо!

**Comment by AlexeyPetroff** [comment]
tags = {str.lower((tag.decode('ASCII')).strip('#')) for tag in caption.split() if (tag.decode('ASCII')).startswith("#")}


Файл instabot.py, функция like_all_exist_media
tags = {str.lower((tag.decode('ASCII')).strip('#')) for tag in caption.split() if (tag.decode('ASCII')).startswith("#")}
Не хватало декодирования в ASCII

**Comment by LevPasha** [comment]
@AlexeyPetroff ок, ждем как народ отпишется о тестах, спасибо!

Guys, please make some test!

**Comment by LevPasha** [comment]
@AlexeyPetroff добавил в последнюю сборку, спасибо!

**Comment by lucianopalhares** [comment]
@LevPasha thanks so much, I worked very well..I ask you, can I share this code case there are so much people searching for this help, thanks advance!

**Pull request closed without merging**
