### PR TITLE
Generate log txt file

### PR DESCRIPTION
**Pull request by linkfy**
Generate log txt file with the last operations. (50~ last lines). Useful for server propose.
The name of the output file is the same as the script file used.

### CODE REVIEW

**Comment by LevPasha** [comment]
There is write_log function, that doing same... Or i miss something?

**Comment by linkfy** [comment]
write_log writes to screen I think, and writeOutput writes to txt file.

**Comment by LevPasha** [comment]
@linkfy there is some mode of write, some write to log file.

**Comment by LevPasha** [comment]
@linkfy https://github.com/LevPasha/instabot.py/blob/master/src/instabot.py#L769

**Comment by linkfy** [comment]
thank you! didn't saw it

**Comment by LevPasha** [comment]
@linkfy someone say it don't work on WIN, you can test it and fix if you want.

**Comment by slimline33** [comment]
Hi, sorry for pirating this issue, but i would write the log in a ramdisk. Is there a way to set the path?

**Pull request closed without merging**
