### PR TITLE
move the party to src

### PR DESCRIPTION
**Pull request by kemong**

### CODE REVIEW

**Comment by TTAAEELL** [comment]
Traceback (most recent call last):
  File "C:\Users\Tael\Desktop\instabot\example.py", line 4, in <module>
    from src.instabot import InstaBot
  File "C:\Users\Tael\Desktop\instabot\src\instabot.py", line 4, in <module>
    from userinfo import UserInfo
ImportError: No module named 'userinfo'

**Comment by kemong** [comment]
do you have file userinfo.py inside src folder? if you use the older zip, the userinfo.py file should be in the same folder as instabot.py

**Comment by TTAAEELL** [comment]
@kemong I just downloaded whole package zip from your repository now. All files are in src except example.py

**Comment by kemong** [comment]
@TTAAEELL first try to extract this into your src folder
if it doesn't work, let me know
[userinfo.py.zip](https://github.com/LevPasha/instabot.py/files/528468/userinfo.py.zip)

**Comment by TTAAEELL** [comment]
@kemong Didn't worked.

**Comment by kemong** [comment]
@TTAAEELL okay calm down... try this then..extract in different folder don't mix with the old files. it works on my Linux PC
[instabot.py.zip](https://github.com/LevPasha/instabot.py/files/528476/instabot.py.zip)

**Comment by kemong** [comment]
@TTAAEELL if it doesn't work
you have to configure your PythonPath try to visit this site then :
http://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-7

**Comment by TTAAEELL** [comment]
@kemong This one works fine and I had it already. I just wanted to try new structure of files and src folder.

BTW, can you please write a complete guide of your mod? It is a little bit complicated to understand it's logic.

I also have request, make a mod to like all posts in feed. Thanks for your work.
#https://github.com/LevPasha/instabot.py/issues/197

**Comment by kemong** [comment]
@TTAAEELL the problem i encounter while creating protocol to like my own feed is, when my following don't active. So posibbly your bot just liking the same photos all day long. It's possible to verify if your bot has already like that photo or not. But my feed are not crowded all day long, so i don't create feed-liker feature. I'll try to add the feature in the next pull. 

Here is a little bit guide of the modes :
"# MODE 0 = ORIGINAL MODE BY LEVPASHA
>>Like photos based on tag you've provided, follow the people who upload it, and make comments

"## MODE 1 = MODIFIED MODE BY KEMONG
>>The bot will figure out, do you have more following then follower? if yes then start unfollowing people who doesn't follow you back. The opposite the bot will start to find people who like photos on your feed, put them into a list. Check those people profile, name, and make sure you follow people with higher chance of getting follow back before sending a follow request.

"### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK
>>Same as method one plus you unfollow people who don't follow you back

"#### MODE 3 = MODIFIED MODE : UNFOLLOW PEOPLE WHO DON'T FOLLOW BACK
>>The bot will try to open your recent feed. It will check the account who upload the photo, if the account follow you, the bot will ignore him/her. If the account don't follow you, the bot will left him/her a few like on his/her photos before sending unfollow request.

"##### MODE 4 = MODIFIED MODE : FOLLOW PEOPLE BASED ON RECENT FEED
>>Eg. Mozart upload a photo, his photo is in your feed. The bot will open Mozart profile. From mozart profile, the bot will choose randomly one of his photo. The bot find out that Da Vinci likes Mozart Photo, so the bot put Da Vinci ID into list. Before sending follow request to Da Vinci, the bot will make a simple check whether Da Vinci worth to follow or not. If Da Vinci only a fake account, the bot will kick his ass from the list.

"###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY
>>That's it unfollow everybody

**Comment by TTAAEELL** [comment]
So your follow/unfollow policy doesn't have any relations to tags? If not, how it will collect best followers?

For example, I have an account for my cat. I want to have followers who have cat or like cats but your script doesn't work based on tags and only looks for people based on following/followers numbers. Am I right?

A feed liker will be good, because many of followers expect to like their posts and show reactions to them. We don't have time to sit and see and like our feed if we have lots of followings, so if bot do that it will be great.

Thanks.

**Comment by kemong** [comment]
@TTAAEELL well, because i design this modified bot for OnlineShops owner. I help them to interact with a lot of people, i tell them that i can't give follower by numbers, i just help them to keep interact with new people everyday. I give my focus to help them find new active people everyday that's why in my policy i choose to reject Celebgram/ Fake Account/ Passive Account. By interacting with new and active people everyday, i wish that i could help them sell their own product. Because, fake follower don't buy your goods, active accounts are potential buyer. That's the philosophy of this mod.

**Comment by LevPasha** [comment]
@kemong Can't merge it. "This branch has conflicts that must be resolved".

**Pull request closed without merging**
