### PR TITLE
Media node JSON correction

### PR DESCRIPTION
**Pull request by ChipWolf**
They appear to have changed this again, this function should probably be made 'smarter' at some point and hunt for username/id patterns in the results

I've tested my changes against mode 1, probably not as thoroughly as I'd like to, but it's getting late.
I will at some point run through the entire project and have a major tidy up when I have a chance.

### CODE REVIEW

**Comment by shurco** [comment]
This commit works for me

**Comment by luisramirez-m** [comment]
This it work for me whit:
mode = 0
mode = 1
mode = 2

Thanks!

**Comment by ChipWolf** [comment]
Np, I'll have a look at the other modes when I have a chance.
I want to implement saving state to file between runs.

**Comment by ChipWolf** [comment]
@LevPasha could you possibly throw instabot.py into a GitHub org and add me to it? It'd help with collaboration.
Similar to how I used to run https://github.com/flibber

**Pull request merged**
